// <auto-generated />
using ApiFutsal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFutsal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiFutsal.Models.Camisa", b =>
                {
                    b.Property<int>("CamisaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CamisaId"));

                    b.Property<int>("CamisaNumero")
                        .HasColumnType("int");

                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.HasKey("CamisaId");

                    b.ToTable("Camisa");

                    b.HasData(
                        new
                        {
                            CamisaId = 1,
                            CamisaNumero = 1,
                            JogadorId = 1
                        },
                        new
                        {
                            CamisaId = 2,
                            CamisaNumero = 2,
                            JogadorId = 2
                        },
                        new
                        {
                            CamisaId = 3,
                            CamisaNumero = 3,
                            JogadorId = 3
                        },
                        new
                        {
                            CamisaId = 4,
                            CamisaNumero = 4,
                            JogadorId = 4
                        },
                        new
                        {
                            CamisaId = 5,
                            CamisaNumero = 5,
                            JogadorId = 5
                        },
                        new
                        {
                            CamisaId = 6,
                            CamisaNumero = 6,
                            JogadorId = 6
                        },
                        new
                        {
                            CamisaId = 7,
                            CamisaNumero = 7,
                            JogadorId = 7
                        },
                        new
                        {
                            CamisaId = 8,
                            CamisaNumero = 8,
                            JogadorId = 8
                        },
                        new
                        {
                            CamisaId = 9,
                            CamisaNumero = 9,
                            JogadorId = 9
                        },
                        new
                        {
                            CamisaId = 10,
                            CamisaNumero = 10,
                            JogadorId = 10
                        },
                        new
                        {
                            CamisaId = 11,
                            CamisaNumero = 11,
                            JogadorId = 11
                        });
                });

            modelBuilder.Entity("ApiFutsal.Models.Jogadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "509885211-11",
                            Nome = "Gustavo Almeida",
                            Posicao = 1,
                            Responsavel = "Isrraela"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "455202582-27",
                            Nome = "Heverson",
                            Posicao = 1,
                            Responsavel = "Cindir"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "523648782-19",
                            Nome = "Cauã",
                            Posicao = 3,
                            Responsavel = "Daniela"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "485213251-15",
                            Nome = "Matheus",
                            Posicao = 3,
                            Responsavel = "Carmem"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "502202144-46",
                            Nome = "Kauan",
                            Posicao = 2,
                            Responsavel = "Aline"
                        },
                        new
                        {
                            Id = 6,
                            CPF = "648558967-79",
                            Nome = "Daniel",
                            Posicao = 2,
                            Responsavel = "Lurdes"
                        },
                        new
                        {
                            Id = 7,
                            CPF = "002147858-44",
                            Nome = "Luan",
                            Posicao = 2,
                            Responsavel = "Cleide"
                        },
                        new
                        {
                            Id = 8,
                            CPF = "124525428-88",
                            Nome = "Kaue",
                            Posicao = 2,
                            Responsavel = "Charlene"
                        },
                        new
                        {
                            Id = 9,
                            CPF = "889652125-45",
                            Nome = "Weverton",
                            Posicao = 4,
                            Responsavel = "Geraldina"
                        },
                        new
                        {
                            Id = 10,
                            CPF = "551031366-84",
                            Nome = "Gustavo",
                            Posicao = 4,
                            Responsavel = "Erismelk"
                        },
                        new
                        {
                            Id = 11,
                            CPF = "554102123-54",
                            Nome = "Lucas",
                            Posicao = 4,
                            Responsavel = "Tatiana"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
